### ISSUE TITLE
Linux_Settingup Feedback Request

### ISSUE THREAD

**Issue by archana-sekarr** [TechGrounds-Cloud8/cloud8-archana-sekarr#2]
**Feedback Request [Linux_Settingup]**
Permalink to file: [[LINK](https://github.com/TechGrounds-Cloud8/cloud8-archana-sekarr/blob/main/DAY2/SETTINGUP.md)]

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by benbui797** [comment]
**Summary**
- Does the summary describe the subject matter fully? 
 yes
- Is the summary written in own words? 
 yes
- Is there crucial information missing in the summary?
 no
- Is the description clear enough?
yes 

**Key Terminology**
- Are there missing key terms?
 no 
- Are the key terms explained well?
n/a

**Sources**
- Are the sources mentioned?
 yes
- Are the mentioned sources correct?
yes 

**Excercise**
(Where applicable)
- Is the result correct?
yes 
- Are the experienced problems and solutions described well?
yes

**Feedback:**
"Linux can be run in your own computer using a virtual machine (VM)" is not 100% correct. 

You could run Windows or Mac on a VM aswell, and your own computer could have Linux as an operating system. They are not explicitely linked.

**Comment by archana-sekarr** [comment]
Thank you for the feedback. I understand it better now.

**Comment by pprasing** [comment]
**Summary**
- Does the summary describe the subject matter fully? yes
- Is the summary written in own words?yes
- Is there crucial information missing in the summary? no not for this entry level 
- Is the description clear enough?yes

**Key Terminology**
- Are there missing key terms? no 
- Are the key terms explained well? yes

**Sources**
- Are the sources mentioned? yes
- Are the mentioned sources correct? yes

**Excercise**
(Where applicable)
- Is the result correct? yes
- Are the experienced problems and solutions described well? yes

currently i noticed the linking is not correct anymore, you might have changed something so i cannot see the pictures anymore, further great job!
