### ISSUE TITLE
LNX-02Feedback Request:LNX-02

### ISSUE THREAD

**Issue by archana-sekarr** [TechGrounds-Cloud8/cloud8-archana-sekarr#3]
**Feedback Request [LNX-02]**
Permalink to file: [[LINK](https://github.com/TechGrounds-Cloud8/cloud8-archana-sekarr/blob/main/week%201/DAY2_LINUX/LNX-02/Filesanddirectories.md)]

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by pprasing** [comment]
**Summary**
- Does the summary describe the subject matter fully? yes
- Is the summary written in own words? yes
- Is there crucial information missing in the summary? no
- Is the description clear enough? yes explained with details

**Key Terminology**
- Are there missing key terms? no
- Are the key terms explained well? yes

**Sources**
- Are the sources mentioned? yes
- Are the mentioned sources correct? yes

**Excercise**
(Where applicable)
- Is the result correct? yes all requested is published
- Are the experienced problems and solutions described well? yes

**Comment by QuincyTjia** [comment]
**Summary**
- Does the summary describe the subject matter fully? **Yes**
- Is the summary written in own words? **Yes**
- Is there crucial information missing in the summary? **No**
- Is the description clear enough? **Yes**

**Key Terminology**
- Are there missing key terms? **No**
- Are the key terms explained well? **Yes**

**Sources**
- Are the sources mentioned? **Yes**
- Are the mentioned sources correct? **Yes**

**Excercise**
(Where applicable)
- Is the result correct? **Yes**
- Are the experienced problems and solutions described well? **Yes**

**Comment by benbui797** [comment]
**Summary**
- Does the summary describe the subject matter fully? **yes**
- Is the summary written in own words? **yes**
- Is there crucial information missing in the summary? **no, it is very extensive! You also more or less finished the next 2 assignments :) **
- Is the description clear enough? **yes**

**Key Terminology**
- Are there missing key terms? **no**
- Are the key terms explained well? **yes**

**Sources**
- Are the sources mentioned? **yes**
- Are the mentioned sources correct? **yess**

**Excercise**
(Where applicable)
- Is the result correct? **yes**
- Are the experienced problems and solutions described well? **yes**
