### ISSUE TITLE
AWS-01-Global Infrastructure Feedback Request:

### ISSUE THREAD

**Issue by archana-sekarr** [TechGrounds-Cloud8/cloud8-archana-sekarr#30]
**Feedback Request [AWS-01-Global Infrastructure]**
Permalink to file: [[LINK](https://github.com/TechGrounds-Cloud8/cloud8-archana-sekarr/blob/main/AWS-Week1/AWS-01-GlobalInfrastructure.md)]

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by Killian97** [comment]
very well done. i really like the very clear and wide explanations. i also see that you really read what you google since you found out about cloudfont and route 53. and you also explain it, not in exercise but you did it.
well done :D

**Comment by QuincyTjia** [comment]
**Summary**
- Does the summary describe the subject matter fully? **Yes**
- Is the summary written in own words? **Yes**
- Is there crucial information missing in the summary? **No**
- Is the description clear enough? **Yes**

**Key Terminology**
- Are there missing key terms? **No**
- Are the key terms explained well? **Yes**

**Sources**
- Are the sources mentioned? **Yes**
- Are the mentioned sources correct? **Yes**

**Excercise**
(Where applicable)
- Is the result correct? **Yes, really well described**
- Are the experienced problems and solutions described well? **Yes**

**Comment by Rolfsijtema** [comment]
Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully? Y
- Is the summary written in own words? Y
- Is there crucial information missing in the summary? N
- Is the description clear enough? Y

**Key Terminology**
- Are there missing key terms?  N
- Are the key terms explained well? Y

**Sources**
- Are the sources mentioned? Y
- Are the mentioned sources correct? Y

**Excercise**
(Where applicable) 
- Is the result correct?  Y
- Are the experienced problems and solutions described well?  Y

**Comment by Rolfsijtema** [comment]
Oregon is the Cheapest region ;)

**Comment by archana-sekarr** [comment]
> Oregon is the Cheapest region ;)

I will keep that in mind :D
