### ISSUE TITLE
AWS-08-Security Groups Feedback Request:

### ISSUE THREAD

**Issue by archana-sekarr** [TechGrounds-Cloud8/cloud8-archana-sekarr#37]
**Feedback Request [AWS-08-Security Groups]**
Permalink to file: [[LINK](https://github.com/TechGrounds-Cloud8/cloud8-archana-sekarr/blob/main/AWS-Week1/AWS-08-SecurityGroups.md)]

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by Killian97** [comment]
because you talk about a statefull firewall i would also talk about stateless firewalls, for the rest, nice explanations. nothing to add
