### ISSUE TITLE
Python -08 Feedback Request:

### ISSUE THREAD

**Issue by archana-sekarr** [TechGrounds-Cloud8/cloud8-archana-sekarr#61]
**Feedback Request [Python -08]**
Permalink to file: [

(https://github.com/TechGrounds-Cloud8/cloud8-archana-sekarr/blob/main/Python/PRG-08-Key-value%20pairs1.py)

https://github.com/TechGrounds-Cloud8/cloud8-archana-sekarr/blob/main/Python/PRG-08-Key-value%20pairs2.py]

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by benbui797** [comment]
Good job!!

**Comment by QuincyTjia** [comment]
Looks good! Nothing to add
