### ISSUE TITLE
LNX-08-Cron jobs Feedback Request:

### ISSUE THREAD

**Issue by archana-sekarr** [TechGrounds-Cloud8/cloud8-archana-sekarr#9]
**Feedback Request [LNX-08-Cron jobs]**
Permalink to file: [[LINK](https://github.com/TechGrounds-Cloud8/cloud8-archana-sekarr/blob/main/week%201/Day3_LINUX/LNX-08/Cron%20jobs.md)]

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by benbui797** [comment]
**Summary**
- Does the summary describe the subject matter fully? **yes**
- Is the summary written in own words? **yes**
- Is there crucial information missing in the summary? **no**
- Is the description clear enough? **yes**

**Key Terminology**
- Are there missing key terms? **no**
- Are the key terms explained well? **yes**

**Sources**
- Are the sources mentioned?  **yes**
- Are the mentioned sources correct? **yes**

**Excercise**
(Where applicable)
- Is the result correct? **yes, but for the last exercise, you have to add the diskspace info to a log file. Tip: There is a specific command available for exactly this purpose. **
- Are the experienced problems and solutions described well? **yes**

**Comment by pprasing** [comment]
**Summary**
- Does the summary describe the subject matter fully? yes
- Is the summary written in own words?yes 
- Is there crucial information missing in the summary? no
- Is the description clear enough? yes

**Key Terminology**
- Are there missing key terms? no
- Are the key terms explained well? yes

**Sources**
- Are the sources mentioned?yes
- Are the mentioned sources correct? yes

**Excercise**
(Where applicable)
- Is the result correct? yes except for the last question, this is not written to a log file yet
- Are the experienced problems and solutions described well? yes

**Comment by archana-sekarr** [comment]
> **Summary**
> 
> * Does the summary describe the subject matter fully? **yes**
> * Is the summary written in own words? **yes**
> * Is there crucial information missing in the summary? **no**
> * Is the description clear enough? **yes**
> 
> **Key Terminology**
> 
> * Are there missing key terms? **no**
> * Are the key terms explained well? **yes**
> 
> **Sources**
> 
> * Are the sources mentioned?  **yes**
> * Are the mentioned sources correct? **yes**
> 
> **Excercise** (Where applicable)
> 
> * Is the result correct? **yes, but for the last exercise, you have to add the diskspace info to a log file. Tip: There is a specific command available for exactly this purpose.** Thank you for the explanation. will try to make the changes.
> * Are the experienced problems and solutions described well? **yes**
